[INFO] [launch]: All log files can be found below /root/.ros/log/2025-02-18-15-06-05-045997-drone-home-331
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [cv_controller-1]: process started with pid [333]
[INFO] [controller-2]: process started with pid [335]
[INFO] [pwm_publisher-3]: process started with pid [337]
[INFO] [gps_publisher-4]: process started with pid [339]
[INFO] [imu_publisher-5]: process started with pid [341]
[INFO] [drive_hardware-6]: process started with pid [343]
[cv_controller-1] [INFO] [1739909166.144357513] [drone_home1.sim]: CV Controller running
[controller-2] [INFO] [1739909166.288834099] [drone_home1.controller]: Controller running
[imu_publisher-5] [INFO] [1739909167.528524848] [drone_home1.imu_publisher]: Calibration status: (True, 'Calibration (sys:0, gyro:0, accel:3, mag:0)')
[cv_controller-1] Traceback (most recent call last):
[cv_controller-1]   File "/workspaces/drone_home-dev/drone-home/ros2_ws/install/drone_home/lib/drone_home/cv_controller", line 33, in <module>
[cv_controller-1]     sys.exit(load_entry_point('drone-home==0.0.0', 'console_scripts', 'cv_controller')())
[cv_controller-1]   File "/workspaces/drone_home-dev/drone-home/ros2_ws/install/drone_home/lib/python3.10/site-packages/drone_home/cv_controller.py", line 72, in main
[cv_controller-1]     rclpy.spin(controller)
[cv_controller-1]   File "/opt/ros/humble/install/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 226, in spin
[cv_controller-1]     executor.spin_once()
[cv_controller-1]   File "/opt/ros/humble/install/local/lib/python3.10/dist-packages/rclpy/executors.py", line 739, in spin_once
[cv_controller-1]     self._spin_once_impl(timeout_sec)
[cv_controller-1]   File "/opt/ros/humble/install/local/lib/python3.10/dist-packages/rclpy/executors.py", line 736, in _spin_once_impl
[cv_controller-1]     raise handler.exception()
[cv_controller-1]   File "/opt/ros/humble/install/local/lib/python3.10/dist-packages/rclpy/task.py", line 239, in __call__
[cv_controller-1]     self._handler.send(None)
[cv_controller-1]   File "/opt/ros/humble/install/local/lib/python3.10/dist-packages/rclpy/executors.py", line 437, in handler
[cv_controller-1]     await call_coroutine(entity, arg)
[cv_controller-1]   File "/opt/ros/humble/install/local/lib/python3.10/dist-packages/rclpy/executors.py", line 351, in _execute_timer
[cv_controller-1]     await await_or_execute(tmr.callback)
[cv_controller-1]   File "/opt/ros/humble/install/local/lib/python3.10/dist-packages/rclpy/executors.py", line 107, in await_or_execute
[cv_controller-1]     return callback(*args)
[cv_controller-1]   File "/workspaces/drone_home-dev/drone-home/ros2_ws/install/drone_home/lib/python3.10/site-packages/drone_home/cv_controller.py", line 53, in control_loop
[cv_controller-1]     drive_msg.drive.steering_angle = steering_angle
[cv_controller-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/ackermann_msgs/msg/_ackermann_drive.py", line 147, in steering_angle
[cv_controller-1]     assert \
[cv_controller-1] AssertionError: The 'steering_angle' field must be of type 'float'
[ERROR] [cv_controller-1]: process has died [pid 333, exit code 1, cmd '/workspaces/drone_home-dev/drone-home/ros2_ws/install/drone_home/lib/drone_home/cv_controller --ros-args -r __node:=sim -r __ns:=/drone_home1'].
